##Determines the number of genes in each module generated by WGCNA##
##Creates a .csv file for each module generated by WGCNA containing the genes in that module##
##Output files are named by the color name of the module##
## --outputdir field should include a "/" at the end ##

library(optparse)

#Initializes argumnets for command line
option_list = list(make_option(c("-d", "--datainput"), help="Gene expression data used for module detection by WGCNA"), 
	make_option(c("-m", "--moddata"), help = "Module data generated by WGCNA"),
	make_option(c("-o", "--outputdir"), help = "Output directory"))
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser)
file1 = opt$datainput
file2 = opt$moddata
dir = opt$outputdir

#Sets working directory so all output files are written here
setwd(dir)

#Loads data
cnames = load(file1)
dnames = load(file2)
print(cnames)
print(dnames)

#Creates new matrix to store one of each module color
length = length(MEs)
moduleColors_no_repeats = rep(NA, length)

#Loads module colors into matrix
n = 0
for (color in moduleColors) {
	if (color %in% moduleColors_no_repeats==FALSE){
		n = n + 1
		moduleColors_no_repeats[n] = color
	}
}
print(length(moduleColors_no_repeats))
print(moduleColors_no_repeats)

#Creates data frame to store module colors and number of genes in each module
module_data = data.frame(matrix(ncol = 1, nrow = length(moduleColors_no_repeats)+1), row.names = c(noquote(moduleColors_no_repeats), "SUM")) 
print(module_data)

#Counts number of genes in each module and stores in data frame
n = 0
for (color in moduleColors_no_repeats){
	n = n + 1
	no_genes = length(names(data_2)[moduleColors==color])
	module_data[n, 1] = no_genes
}	

#Calculates sum of all genes
#Sum should be the same as the number of genes used for coexpression analysis with WGCNA
sum = sum(module_data[1:length(moduleColors_no_repeats),1])
print(sum)
module_data[length(moduleColors_no_repeats)+1,1] = sum

#Writes file containing completed data frame
print(module_data)
write.table(module_data, file = "module_data.txt", row.names = TRUE, sep = "\t", quote = FALSE)

#Creates a .csv file containing the genes in each module
for (number in 1:(dim(module_data)[1]-1)){
	selected_module = rownames(module_data)[number]
	#print(number)
	#print(selected_module)
	module_genes = names(data_2)[moduleColors==selected_module]
	#print(module_genes[1:5])
	write.csv(module_genes, file = sprintf("%s_genes.csv", selected_module), quote=FALSE, row.names=FALSE)
}	

