library(optparse)

option_list = list(make_option(c("-d", "--datainput"), help="Gene expression data used for module detection by WGCNA"), 
	make_option(c("-m", "--moddata"), help = "Module data generated by WGCNA"),
	make_option(c("-t", "--traits"), help = "Traits associated with samples. ie relative water content, pot weight, etc."),
	make_option(c("-o", "--outputdir"), help = "Output directory"))
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser)
file1 = opt$datainput
file2 = opt$moddata
traits = opt$traits
dir = opt$outputdir

setwd(dir)

library(WGCNA)
options(stringsAsFactors = FALSE)

cnames = load(file1)
dnames = load(file2)
print(traits)
traits_table = read.table(traits, header = TRUE, sep = ",", row.names=1)
print(cnames)
print(dnames)

no_genes = ncol(data_2)
no_samples = nrow(data_2)

mes_order = orderMEs(MEs)

print(dim(mes_order))
print(dim(traits_table))
print(head(traits_table))
mod_trait_cor = cor(mes_order, traits_table, use = "p")
mod_trait_p = corPvalueStudent(mod_trait_cor, no_samples)

print(head(mod_trait_cor))

write.table(mod_trait_cor, "trait_cor_matrix.txt", sep = "\t", quote=FALSE)

"""
#sizeGrWindow(10,1)
# Will display correlations and their p-values
textMatrix = paste(signif(mod_trait_cor, 2), "\n(",
	signif(mod_trait_p, 1), ")", sep = "");
dim(textMatrix) = dim(mod_trait_cor)
print(mes_order)
print(mod_trait_cor)
# Display the correlation values within a heatmap plot
par(mar=c(4,5,5,6))
png("trait_comparison.png", width=800, height=600)
labeledHeatmap(Matrix = mod_trait_cor,
	xLabels = names(traits_table),
	yLabels = names(mes_order),
	ySymbols = names(mes_order),
	colorLabels = FALSE,
	colors = greenWhiteRed(50),
	textMatrix = textMatrix,
	setStdMargins = FALSE,
	cex.text = 0.5,
	zlim = c(-1,1),
	main = paste("Module-trait relationships"))
par(mar=c(4,5,5,6))
png("trait_comparison.png", width=800, height=800)
dev.off()
"""
